# Generated by Django 6.0.5 on 2026-09-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsp_billing", "0003_invoice_payment_url_length"),
        ("dsp_payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="entitlement",
            field=models.ForeignKey(
                blank=True,
                help_text="Доступ, срок которого продлевается/отзывается по статусу подписки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stripe_subscriptions",
                to="dsp_billing.userentitlement",
            ),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="payment_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past due"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete expired"),
                    ("trialing", "Trialing"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                default="incomplete",
                max_length=32,
            ),
        ),
    ]
