# Generated by Django 6.0.5 on 2026-05-30 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsp_billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='balanceledger',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('reference',), name='dsp_unique_ledger_reference'),
        ),
    ]
