# Generated by Django 6.0.5 on 2026-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsp_billing", "0002_ledger_reference_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
